FROM python:3.11-slim

WORKDIR /app

RUN pip install install Flask requests

RUN pip install PyPDF2 

RUN pip install python-dotenv

RUN pip install pymongo

COPY text_extractor/. .

CMD ["python", "-u", "main.py"]
